# Generated by Django 2.2.17 on 2021-02-02 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReferrerCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_referrer_code', to=settings.AUTH_USER_MODEL)),
                ('referrer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referrer code',
                'db_table': 'user_referrer_code',
                'unique_together': {('owner_user', 'referrer_user')},
            },
        ),
    ]
