# Generated by Django 2.2.17 on 2021-02-08 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userreferrercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreferrercode',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
